### ISSUE TITLE
nodenv-installer should not return a non-zero status code on installation

### ISSUE THREAD

**Issue by llimllib** [nodenv/nodenv-installer#8]
What I see:

* Start from a base OS
* Install nodenv per the instructions, and note that the script returns a failure status code:

```
$ curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-installer | bash
Installing nodenv with git...
Initialized empty Git repository in /home/vagrant/.nodenv/.git/
Updating origin
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 3670 (delta 0), reused 6 (delta 0), pack-reused 3664
Receiving objects: 100% (3670/3670), 644.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2447/2447), done.
From https://github.com/nodenv/nodenv
 * [new branch]      master     -> origin/master
 * [new tag]         0.2.0      -> 0.2.0
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.2.0     -> v0.2.0
 * [new tag]         v0.3.0     -> v0.3.0
 * [new tag]         v0.4.0     -> v0.4.0
 * [new tag]         v1.0.0     -> v1.0.0
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.1.1     -> v1.1.1
 * [new tag]         v1.1.2     -> v1.1.2
 * [new tag]         v1.2.0     -> v1.2.0
Branch master set up to track remote branch master from origin.
Already on 'master'
make: Entering directory '/home/vagrant/.nodenv/src'
gcc -fPIC     -c -o realpath.o realpath.c
gcc -shared -Wl,-soname,../libexec/nodenv-realpath.dylib  -o ../libexec/nodenv-realpath.dylib realpath.o
make: Leaving directory '/home/vagrant/.nodenv/src'

Installing node-build with git...
Cloning into '/home/vagrant/.nodenv/plugins/node-build'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 16790 (delta 27), reused 44 (delta 16), pack-reused 16735
Receiving objects: 100% (16790/16790), 2.88 MiB | 3.96 MiB/s, done.
Resolving deltas: 100% (10874/10874), done.
Checking connectivity... done.

Running doctor script to verify installation...
Checking for `nodenv' in PATH: not found
  You seem to have nodenv installed in `/home/vagrant/.nodenv/bin', but that
  directory is not present in PATH. Please add it to PATH by configuring
  your `~/.bashrc', `~/.zshrc', or `~/.config/fish/config.fish'.

$ echo $?
1
```

What I expect to see:
* nodenv installs without error

I'm installing nodenv in an automated environment, so the non-zero error from the install script breaks my script.

I can fix the error by adding two as-yet-nonexistent directories to my `PATH`:

```
$ export PATH="$HOME/.nodenv/bin:$HOME/.nodenv/shims:$PATH"
$ rm -rf ~/.nodenv/
$ curl -fsSL https://github.com/nodenv/nodenv-installer/raw/master/bin/nodenv-installer | bash
<snip>
Running doctor script to verify installation...
Checking for `nodenv' in PATH: /home/vagrant/.nodenv/bin/nodenv
Checking for nodenv shims in PATH: not found
  The directory `/home/vagrant/.nodenv/shims' must be present in PATH for nodenv to work.
  Please run `nodenv init' and follow the instructions.

Checking `nodenv install' support: /home/vagrant/.nodenv/plugins/node-build/bin/nodenv-install (node-build 4.4.0-6-gc907722)
Counting installed Node versions: none
  There aren't any Node versions installed under `/home/vagrant/.nodenv/versions'.
  You can install Node versions like so: nodenv install 2.2.4
Auditing installed plugins: OK
$ echo $?
1
```

Would it be possible to have nodenv-installer exit with status 0 on successful completion, and if the user is required to add the future nodenv bin path before running nodenv-installer, to add that to the instructions?

(Preferably, the user would not be required to add a path that doesn't yet exist before running the script, but that's up to you)

(Thanks for nodenv, I like it better than the other options, I don't mean to hate at all. Appreciate the work)

**Comment by jasonkarns** [comment]
Good question. The error is reported by the -doctor script, which is used to detect a "functioning" installation and is used separately from the installer.

It's worth noting that running the installer on macOS with homebrew should result in a successful exit, since the installer would then use homebrew to install nodenv, and therefore nodenv's bin would already be in PATH (IIRC).

Some options:
1. We could add the pre-req steps of updating PATH, such that it's expected to be correct before installing. (as you mentioned)
2. We could have the installer script update PATH _itself_. (feasible, but rather invasive, considering the variety of shell init files and configurations)
3. We could have the installer simply emit a message about the necessary PATH changes and then skip running the doctor.

Honestly, step 3 sounds the best and is essentially what's happening now: the doctor is invoked as a means of reporting any issues with the current installation; and "remaining installation steps" technically fall under that umbrella. I'm wondering aloud if usage would be improved having the installer script exit with a 0 status code, if the result is _not_ a functioning installation (since there are still manual steps that need performed). Perhaps the messaging from the installer could be improved such that it's more clear that remaining steps _may_ be necessary? But if I were to have the installer run in a script or automated fashion, I would expect a 0 exit to indicate successful installation; and without the proper PATH, that's not strictly the case.

Further thoughts?

**Comment by llimllib** [comment]
3 is what makes the most sense to me, plus messaging after the installer exits + documentation here

**Comment by josh08h** [comment]
We are relying on this script to install nodenv on our CI servers. Obviously a non-zero exit code from this installation script is not ideal. I've worked around it by amending `$PATH` with the non-existent `nodenv` requirements.

I'd say 3 makes the most sense.

**Comment by jasonkarns** [comment]
Opened #12 as a slight twist on option 3 above...

Instead of having the installer skip the doctor, we still run the doctor as per usual (no changes to the installer). However, now the doctor detects a "recent" installation and exits cleanly (0). The "recent" installation is detected if the nodenv binary's mtime is <1 min.

I would be most grateful if @llimllib, @josh08h were able to test this before I merge.

**Comment by llimllib** [comment]
How do I test it? I tried doing `curl -fsSL https://github.com/nodenv/nodenv-installer/blob/978b0752c3e067dc475f4c3f7ed7eaad65f69c1b/bin/nodenv-installer | bash`, but got:

```console
   virtualbox-ovf: ++ curl -fsSL https://github.com/nodenv/nodenv-installer/blob/978b0752c3e067dc475f4c3f7ed7eaad65f69c1b/bin/nodenv-installer
    virtualbox-ovf: bash: line 7: syntax error near unexpected token `newline'
    virtualbox-ovf: bash: line 7: `<!DOCTYPE html>'
```

**Comment by jasonkarns** [comment]
@llimllib You have to be sure to curl the raw script, firstly. (The curl above is pulling github's html doc for the script.)

Of course, to fully test it, one would need a nodenv-installer script that curls the doctor script from the PR or branch. So I made that tweak in a branch: https://github.com/nodenv/nodenv-installer/compare/master...test-recent-install

`curl -fsSL https://raw.githubusercontent.com/nodenv/nodenv-installer/test-recent-install/bin/nodenv-installer | bash` should do it.
